### ISSUE TITLE
This is awesome, how can we collaborate?

### ISSUE THREAD

**Issue by Widdershin** [motorcyclejs/collection#2]
Super duper cool!

I've been thinking about how we might manage collections in a stream library agnostic way. Can you think of a way we could implement something like this so that we can share a codebase for xstream/rx/most? or is it something specific enough to a particular stream library that it's not worth doing.

**Comment by axefrog** [comment]
Hey thanks for taking a look! I'm certainly open to collaboration, however I think you'll find the implementation here is quite dependent on most in this case. One of the features of the library was to preserve open streams when the list changes. A basic approach would cause old subscriptions to drop and new subscriptions to be created. I imagine this is probably less of an issue with xstream due to the fact that it is multicasted by default, and I have some vague recollection of a feature where it waits a tick before dropping a subscription in case of immediate resubscription? not sure, but in most, multicast is an opt-in feature, so I had to write a custom combinator to handle that (see [switch-collection.js](https://github.com/motorcyclejs/collection/blob/master/src/switch-collection.js)).

I imagine there is the potential to handle this purely through the ES7 Observable interface and do everything imperatively under the hood, but having just spent the last two weeks on this, I'm anxious to get back to finishing my current main project, which is a visualiser for most and motorcycle applications, so reworking the architecture right now is something that's not hugely motivating for me right at the moment. That said, I'm definitely open to discussing it as a future possibility, and exploring what changes might be required to make that happen.

Also, I'm always open to pull requests of course. I should also mention that one of my goals is to show people the power of Most, which I think the Cycle community hasn't really paid too much attention so far, even though it's a perfectly valid option with a mature set of ready-to-use drivers, thanks to @TylorS.

**Comment by Widdershin** [comment]
I'm with you on all of that, especially your desire to get back to making concrete stuff instead of libraries.

Here's my proposed course of action:
- @cycle/collection and @motorcycle/collection remain independent
- We each mould our API to suit the cases that make sense
- We follow each other's repos so we can keep abreast of relevant discussions
- We steal each other's good ideas
- Further down the track, we see if it makes sense for us to expose the same interface, mostly for the sake of familiarity

How does that sound?

**Comment by axefrog** [comment]
Sounds good to me. I already stole your good ideas, so you should probably do the same :D
